name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the 
      run: mkdir test
    - name: Build the Docker image
      run: curl https://raw.githubusercontent.com/airbnb/javascript/master/package.json > test.txt
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
          name: code-coverage-report
          path: test.txt
